config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root "profile#index"

    get "logs/from_controllers",     to: "logs#from_controllers"
    get "logs/from_controllers/all", to: "logs#from_controllers_all"
    get "logs/from_file",            to: "logs#from_file"
    get "logs/from_file/all",        to: "logs#from_file_all"

    get    'session', to: "session#index"
    post   'session', to: "session#create"
    delete 'session', to: "session#destroy"
  end
  
  root 'converter#index'

  resources :products do
    member do
      get  "add_photo", action: :add_photo_form
      post "add_photo"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/filter_form.rb
module FilterForm
  def filter_form attrs
    logs = all
    logs = logs.where("id = ?", attrs[:id]) if attrs[:id]

    if attrs[:ip]
      logs = logs.where("remote_ip LIKE ?", "%" + attrs[:ip] + "%")
    end

    if attrs[:get_parameters]
      logs = logs.where("query_string LIKE ?", "%" + attrs[:get_parameters] + "%")
    end

    logs = logs.where("method = ?", attrs[:method]&.upcase) if attrs[:method]

    if attrs[:request_id]
      logs = logs.where("request_id LIKE ?", "%" + attrs[:request_id] + "%")
    end

    if attrs[:path] && attrs[:exact_path] == "1"
      logs = logs.where("path = ?", attrs[:path])
    elsif attrs[:path]
      logs = logs.where("path LIKE ?", "%" + attrs[:path] + "%")
    end

    if attrs[:post_parameters]
      logs = logs.where("request_parameters LIKE ?", "%" + attrs[:post_parameters] + "%")
    end

    logs
  end
end

app/models/file_logs.rb
class FileLogs
  def initialize(path)
    @path = Rails.application.root + path
  end

  def all
    File.readlines(@path)
  end

  def filter_logs str
    if str.class == String
      all.select { |log| log.downcase.include?(str.downcase) }
    else
      all
    end
  end
end

app/models/log.rb
class Log < ApplicationRecord
  extend FilterForm
end

app/models/product.rb
class Product < ApplicationRecord
  has_many_attached :photos
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
    before_action :authenticate_admin

    def authenticate_admin
        unless session[:admin]
            flash[:error] = "Вы должны войти, чтобы получить доступ"
            redirect_to admin_session_path
        end
    end
end

app/controllers/admin/logs_controller.rb
class Admin::LogsController < Admin::AdminController
  include Pagination

  def from_controllers
    @logs = Log.order(:created_at).filter_form(filter_params)

    @page_size    = get_a_page_size
    @last_page    = get_a_last_page(@logs.count)
    @current_page = get_a_current_page
    
    @logs = @logs.offset(get_an_offset).limit(@page_size)
  end

  def from_controllers_all
    @logs = Log.order(:created_at).filter_form(filter_params)
  end

  def from_file
    @logs = FileLogs.new("log/#{Rails.env}.log").filter_logs(params[:filter])

    @page_size    = get_a_page_size
    @last_page    = get_a_last_page(@logs.size)
    @current_page = get_a_current_page

    @logs = @logs[get_an_offset, @page_size]
  end

  def from_file_all
    @logs = FileLogs.new("log/#{Rails.env}.log").filter_logs(params[:filter])
  end


  private
    def filter_params 
      attrs = [ :id, :ip, :get_parameters, :method, :request_id, :path, 
                :exact_path, :post_parameters ].map(&:to_s)

      params.select { |key, value| attrs.include?(key) and !(value.strip.empty?) }
    end
end

app/controllers/admin/profile_controller.rb
class Admin::ProfileController < Admin::AdminController
  def index
  end
end

app/controllers/admin/session_controller.rb
class Admin::SessionController < Admin::AdminController
  skip_before_action :authenticate_admin, only: [:index, :create]

  def index
  end

  def create
    admin    = Rails.application.credentials.admin.login
    password = Rails.application.credentials.admin.password

    if params[:login] == admin and params[:password] == password
      session[:admin] = true

      SendEmailJob.perform_later(request.remote_ip)

      redirect_to admin_root_path
    else
      @login            = params[:login]
      flash.now[:error] = 'Неверный логин или пароль.'
      
      render :index
    end
  end

  def destroy
    session[:admin] = nil
    redirect_to admin_session_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :add_log

    private
        def add_log
            Log.create(
                remote_ip:          request.remote_ip,
                request_id:         request.request_id,
                method:             request.method,
                path:               request.path,
                query_string:       request.query_string,
                request_parameters: request.request_parameters 
            )
        end
end

app/controllers/concerns/pagination.rb
module Pagination 
  def get_a_current_page
    page = (params[:current_page]&.match(/\A\d+/)&.to_s&.to_i || 1)
    page = 1 if page == 0
    page > @last_page ? @last_page : page
  end

  def get_a_last_page(total_elements)
    page  = total_elements / @page_size
    page += 1 unless (total_elements % @page_size) == 0
    page == 0 ? 1 : page
  end

  def get_an_offset
    (@current_page - 1) * @page_size
  end

  def get_a_page_size
    size = params[:page_size]&.match(/\A\d+/)&.to_s&.to_i if params[:page_size]
    
    unless size
      if params[:action] == "from_controllers"
        size = 6
      elsif params[:action] == "from_file"
        size = 20
      end
    end

    size == 0 ? 1 : size
  end
end

app/controllers/converter_controller.rb
class ConverterController < ApplicationController
  def index
    @date = unless [nil , ''].include?(params[:date])
      Date.parse params[:date]
    end

    @expiration_date = unless [nil , ''].include? params[:expiration_date]
      Date.parse params[:expiration_date] 
    end

    @storage_life = unless [nil, ''].include? params[:storage_life]
      params[:storage_life].to_i
    end

    if @date and @expiration_date
      difference = @expiration_date - @date
      @date_of_60_precent = @date + (difference * 0.6).ceil
    elsif @date and @storage_life
      @date_of_60_precent = @date + (@storage_life * 0.6).ceil
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product                   = Product.new
    @product.date_of_rejection = params[:date_of_rejection]
  end

  def create
    @product = Product.create(product_params)
    redirect_to @product
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update(update_product_params)
    redirect_to @product
  end

  def destroy
    Product.destroy_by(id: params[:id])
    redirect_to products_path
  end

  def add_photo_form
    @product = Product.find(params[:id])
  end

  def add_photo
    @product = Product.find(params[:id])
    @product.photos.attach(params[:photo])
    redirect_to @product
  end

  private
    def product_params
      params.require(:product).permit(:plu, :quantity, :type_of_quantity, 
                                      :date_of_rejection, :photos)
    end

    def update_product_params 
      params.require(:product).permit(:plu, :quantity, :type_of_quantity)
    end
end

app/helpers/admin/logs_helper.rb
module Admin::LogsHelper
    def filter_params
        params.permit(
          :id,
          :ip, 
          :get_parameters, 
          :method, 
          :request_id, 
          :path, 
          :post_parameters,
          :exact_match,
          :commit
        )
    end
end

app/helpers/admin/profile_helper.rb
module Admin::ProfileHelper
end

app/helpers/admin/session_helper.rb
module Admin::SessionHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/converter_helper.rb
module ConverterHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/logs/_filter_form.html.erb
<details <%= "open" if params[:id]%>>
    <summary>Отфильтровать логи</summary>
    <%= form_with url: url, method: :get do |form| %>
        <p>
        <%= form.number_field :id, value: params[:id] %>
        <%= form.label :id, " - id" %>
        </p>
        <p>
        <%= form.text_field :request_id, value: params[:request_id] %>
        <%= form.label :request_id, " - request_id"%>
        </p>
        <p>
        <%= form.text_field :ip, value: params[:ip] %>
        <%= form.label :ip, " - ip"%>
        </p>
        <p>
        <%= form.text_field :method, value: params[:method] %>
        <%= form.label :method, " - method"%>
        </p>
        <p>
        <%= form.text_field :path, value: params[:path] %>
        <%= form.label :path, " - path"%>
        </p>
        <p>
        <%= form.check_box :exact_path, checked: (params[:exact_path] == '1' ? true : false) %>
        <%= form.label :exact_path, "Точное совпадение path" %>
        </p>
        <p>
        <%= form.text_field :get_parameters, value: params[:get_parameters] %>
        <%= form.label :get_parameters, " - get параметры"%>
        </p>
        <p>
        <%= form.text_field :post_parameters, value: params[:post_parameters] %>
        <%= form.label :post_parameters, " - post параметры"%>
        </p>
        
        <%= form.hidden_field :page_size, value: @page_size %>

        <%= form.submit "Отфильтровать" %>
    <% end %>
    <br>
    <%= button_to "Очистить", url, method: :get %>
</details>
<hr>

app/views/admin/logs/_log.html.erb
 <p>
  создан: <%= log.created_at %><br>
  последнее обновление: <%= log.updated_at %><br>
  id: <%= log.id %><br>
  request_id: <%= log.request_id %><br>
  ip: <%= log.remote_ip %><br>
  method: <%= log.method %><br>
  path: <%= log.path %><br>
  get параметры: <%= log.query_string %><br>
  post параметры: <%= log.request_parameters %><br>
</p>
<hr>

app/views/admin/logs/_page_size_form.html.erb
<%= form_with url: url, method: :get do |form| %>
    <%= form.label :page_size, "Количество элементов на странице:" %>
    <%= form.text_field :page_size, value: @page_size %>

    <% if params[:id] %>
        <%= form.hidden_field :id,              value: params[:id] %>
        <%= form.hidden_field :ip,              value: params[:ip] %>
        <%= form.hidden_field :get_parameters,  value: params[:get_parameters] %>
        <%= form.hidden_field :method,          value: params[:method] %>
        <%= form.hidden_field :request_id,      value: params[:request_id] %>
        <%= form.hidden_field :path,            value: params[:path] %>
        <%= form.hidden_field :post_parameters, value: params[:post_parameters] %>
        <%= form.hidden_field :exact_match,     value: params[:exact_match] %>
    <% end %>

    <% if params[:filter] %>
        <%= form.hidden_field :filter, value: params[:filter] %>
    <% end %>

    <%= form.hidden_field :current_page, value: @current_page %>

    <%= form.submit "изменить количество элементов" %>
<% end %>

app/views/admin/logs/from_controllers.html.erb
<h2>Логи из контроллера</h2>

<p>
<%= link_to 'Вернуться в панель администратора', admin_root_path %>
<%= link_to(
      'Показать все логи из контроллера одной страницей', 
      admin_logs_from_controllers_all_path(filter_params) 
    )%>
</p>

<%= render "page_size_form", url: admin_logs_from_controllers_path %>

<%= render "filter_form", url: admin_logs_from_controllers_path %>

<div>
    <% @logs.each do |log|%>
        <%= render "log", log: log %>
    <% end %>
</div>

<p>
Страница <%= @current_page %> из <%= @last_page %>

<% unless @current_page == 1 %>
    <%=
    link_to(
      "Начальная страница", 
      admin_logs_from_controllers_path(params: filter_params, page_size: @page_size) 
    )
    %>
<% end %>

<% unless @current_page == @last_page %>
    <%= 
    link_to(
      "Конечная страница", 
      admin_logs_from_controllers_path(params: filter_params, current_page: @last_page,
                                       page_size: @page_size ) 
    )
    %>
<% end %>
</p>

<p>
<% unless @current_page == 1 %>
    <%= 
    link_to(
      "Предыдущая страница(shift + ←)", 
      admin_logs_from_controllers_path(params: filter_params, current_page: @current_page - 1,
                                       page_size: @page_size), 
      id: "left" 
    )
    %> 
<% end %>

<span style="white-space:pre">           </span>

<% unless @current_page == @last_page %>
    <%= 
    link_to(
      "Следующая страница(shift + →)", 
      admin_logs_from_controllers_path(params: filter_params, current_page: @current_page + 1,
                                       page_size: @page_size), 
      id: "right" 
    )
    %>
<% end %>
</p>

<%= form_with url: admin_logs_from_controllers_path, method: :get do |form| %>
    <%= form.submit "Перейти на " %>
    <%= form.number_field :current_page %>
    <% if params[:id] %>
        <%= form.hidden_field :id,              value: params[:id] %>
        <%= form.hidden_field :ip,              value: params[:ip] %>
        <%= form.hidden_field :get_parameters,  value: params[:get_parameters] %>
        <%= form.hidden_field :method,          value: params[:method] %>
        <%= form.hidden_field :request_id,      value: params[:request_id] %>
        <%= form.hidden_field :path,            value: params[:path] %>
        <%= form.hidden_field :post_parameters, value: params[:post_parameters] %>
        <%= form.hidden_field :exact_match,     value: params[:exact_match] %>
        <%= form.hidden_field :page_size,       value: @page_size %>
    <% end %>
<% end %>

app/views/admin/logs/from_controllers_all.html.erb
<h2>Логи из контроллеров одним файлом</h2>

<p>
<%= link_to 'Вернуться в панель администратора', admin_root_path %>

<%= 
link_to(
  'Показать все логи из контроллера постранично', 
  admin_logs_from_controllers_path(params: filter_params) 
)
%>
</p>

<%= render "filter_form", url: admin_logs_from_controllers_all_path %>

<div>
    <% @logs.each do |log|%>
       <%= render "log", log: log %>
    <% end %>
</div>

app/views/admin/logs/from_file.html.erb
<h2>Логи приложения из файла log/production.log</h2>

<p>
<%= link_to 'Вернуться в панель администратора', admin_root_path%>
<%= link_to "Показат все логи одной страницей", admin_logs_from_file_all_path%>

<%= render "page_size_form", url: admin_logs_from_file_path %>

<%= form_with url: admin_logs_from_file_path, method: :get do |form|%>
    <%= form.hidden_field :page_size, value: @page_size %>
    <%= form.text_field :filter, value: params[:filter] %>
    <%= form.submit "Поиск"%>
<% end %>
<%= button_to "Очистить", admin_logs_from_file_path, method: :get %>
</p>

<div>
    <% line_indentation = (@current_page * @page_size).to_s.size %>
    <% @logs.each_with_index do |log, idx| %>
        <% current_line = (@current_page - 1) * @page_size + idx + 1 %>
        <span style="white-space:pre"><%= "#{current_line}#{"  " * (line_indentation - (current_line).to_s.size)} |" %></span>
        <%= log %>
        <br>
    <% end %>
</div>

<p>
Страница <%= @current_page %> из <%= @last_page %>
<% unless @current_page == 1 %>
    <%= link_to(
          "Начальная страница",
          admin_logs_from_file_path(filter: params[:filter], page_size: @page_size) 
        )
    %>
<% end %>
<span style="white-space:pre">     </span>
<% unless @current_page == @last_page %>
    <%= link_to(
          "Конечная страница",
          admin_logs_from_file_path(current_page: @last_page, filter: params[:filter],
                                    page_size: @page_size)
        )
    %>
<% end %>
</p>

<p>
<% unless @current_page == 1 %>
    <%= link_to(
          "Предыдущая страница(shift + ←)",
          admin_logs_from_file_path(current_page: (@current_page - 1), filter: params[:filter],
                                                   page_size: @page_size),
          id: "left"
        )
    %> 
<% end %>

           </span>
<% unless @current_page == @last_page %>
    <%= link_to(
          "Следующая страница(shift + →)", 
          admin_logs_from_file_path(current_page: (@current_page + 1), filter: params[:filter],
                                    page_size: @page_size),
          id: "right"
        )
    %>
<% end %>
</p>

<%= form_with url: admin_logs_from_file_path, method: :get do |form| %>
    <%= form.hidden_field :filter,    value: params[:filter] %>
    <%= form.hidden_field :page_size, value: @page_size %>
    <%= form.submit "Перейти на " %>
    <%= form.number_field :current_page %>
<% end %>

app/views/admin/logs/from_file_all.html.erb
<h2>Логи приложения одной страницей из файла log/production.log</h2>

<p>
<%= link_to 'Вернуться в панель администратора', admin_root_path%>
<%= link_to "Показат все логи постранично", admin_logs_from_file_path%>
<%= form_with url: admin_logs_from_file_all_path, method: :get do |form|%>
    <%= form.text_field :filter, value: params[:filter]%>
    <%= form.submit "Поиск"%>
<% end %>
<%= button_to "Очистить", admin_logs_from_file_path, method: :get %>
</p>

<div>
    <% line_indentation = @logs.size.to_s.size %>
    <% @logs.each_with_index do |log, idx| %>
        <span style="white-space:pre"><%= "#{idx + 1}#{"  " * (line_indentation - (idx+1).to_s.size)} |" %></span>
        <%= log %>
        <br>
    <% end %>
</div>

app/views/admin/profile/index.html.erb
<h1>Панель админа</h1>

<p>
<%= link_to "Логи из контроллера", admin_logs_from_controllers_path %>
</p>

<p>
<%= link_to "Логи приложения из файла log/production.log", admin_logs_from_file_path %>
</p>

<%= button_to 'Выйти', admin_session_path, method: :delete %>

app/views/admin/session/index.html.erb
<% if flash[:error] %>
    <p style="color:red"><%= flash[:error] %></p>
<% end %>

<% if session[:admin] %>
    <%= button_to 'Выйти', admin_session_path, method: :delete %>
<% else %>
    <%= form_with url: admin_session_path do |form| %>
        <%= form.label :login, 'Логин'%>
        <%= form.text_field :login, value: @login %>

        <%= form.label :password, 'Пароль' %>
        <%= form.password_field :password %>

        <%= form.submit "Войти" %>
    <% end %>
<% end %>

app/views/converter/index.html.erb
<div class="container">
<div>
<%= form_with url: "/", method: :get do |form|%>
    <div class='label-text'><%= form.label :date, "Дата изготовления:"%></div>
    <div><%= form.date_field :date, value: params[:date], class: 'size' %></div>
    <% if params[:switch] or @storage_life %>
        <div class='label-text'><%= form.label :storage_life, "Срок годности:"%></div>
        <div><%= form.number_field :storage_life, value: @storage_life, class: 'storage_life' %></div>
    <% else%>
        <div class='label-text'><%= form.label :expiration_date, "Годен до:"%></div>
        <div><%= form.date_field :expiration_date, value: params[:expiration_date], class: :size %></div>
    <% end %>
    <%= form.submit 'рассчитать', class: 'size'%>
<% end %>
</div>



<% if @date_of_60_precent %>
    <div>
        <p class='input'>Браковать c: <div class="text"><%= @date_of_60_precent.strftime "%d - %m - %y" %></div></p>
        <%= button_to 'очистить', '/', method: :get %>
    </div>

    <div>
        <%= button_to "добавить товар на продажу", new_product_path, method: :get, 
                      params: {date_of_rejection: @date_of_60_precent.strftime("%d - %m - %Y") } %>
    </div>
<% end %>

<% if params[:switch] or @storage_life %>
    <div><%= button_to "поменять на дату", '/', method: :get%></div>
<% else %>
    <div>
        <%= button_to "поменять на срок годности", '/', method: :get, params: { switch: true } %>
    </div>
<% end %>

<div>
    <%= button_to "все товары на продажу", products_path, method: :get %>
</div>
</div>

app/views/layouts/admin/logs.html.erb
<!DOCTYPE html>
<html lang="ru">
  <head>
    <title>Converter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <script>
      document.addEventListener('keydown', function(event){
        if (document.getElementById("right") && event.shiftKey && 'ArrowRight' == event.key ) {
          window.location.href = document.getElementById("right").href;
        };

        if (document.getElementById("left") && event.shiftKey && 'ArrowLeft' == event.key ) {
          window.location.href = document.getElementById("left").href;
        };
      });
    </script>
    
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ru">
  <head>
    <title>Converter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/converter.html.erb
<!DOCTYPE html>
<html lang="ru">
  <head>
    <title>Converter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "converter/converter" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/products.html.erb
<!DOCTYPE html>
<html lang="ru">
  <head>
    <title>Converter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "products/products" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/add_photo_form.html.erb
<div>
<%= form_with url: add_photo_product_path(@product) do |form| %>
    <div class="file-upload">
    <label>
        <%= form.file_field :photo, accept: 'image/png,image/gif,image/jpeg',
                            onchange: "getFileName();" %>
        <span id="input-text">выбрать фото</span>
    </label>
    </div>

    <%= form.submit "сохранить" %>
<% end %>
</div>

<div>
    <%= button_to "отменить", product_path(@product), method: :get %>
</div>

<script type="text/javascript">
    function getFileName() {
        document.getElementById('input-text').innerHTML = "фото выбрано";
    }
</script>

app/views/products/edit.html.erb
<div>
<%= form_with model: @product, method: :put do |form| %>
    <div>
        <%= form.hidden_field :date_of_rejection, value: @date_of_rejection %>
        Браковать с: <%= @date_of_rejection %>
    </div>

    <div>
        PLU: <%= form.number_field :plu %>
    </div>

    <div>
        Количество: <%= form.number_field :quantity, min: "0.0", step: "0.001" %>
    </div>

    <div>
        <%= form.radio_button :type_of_quantity, "кг" %>
        <%= form.label :type_of_quantity_кг, 'кг' %>
    </div>

    <div>
        <%= form.radio_button :type_of_quantity, "шт" %>
        <%= form.label :type_of_quantity_шт, 'шт' %>
    </div>

    <%= form.submit "сохранить" %>
<% end %>
</div>

<div>
    <%= button_to "отменить", product_path(@product), method: :get %>
</div>

app/views/products/index.html.erb
<div>
    <%= button_to "вернуться на главную", root_path, method: :get %>
    <hr size="10px" color="green">
</div>

<div>
<% if @products.size == 0 %>
    Нет сохранных товаров
<% else %>
    <% @products.each do |product| %>
        <div>
        Браковать с: <%= product.date_of_rejection %>
        </div>

        <div>
            PLU: <%= product.plu %>
        </div>

        <div>
            Количество: <%= product.quantity %> <%= product.type_of_quantity %>
        </div>

        <div>
            <% if product.photos.last %>
                <%= image_tag product.photos.last %>
            <% end %>
        </div>

        <div>
            <%= button_to "подробнее", product_path(product), method: :get %>
        </div>

        <hr class="separator-hr">
    <% end %>
<% end %>
</div>

app/views/products/new.html.erb
<%= form_with model: @product do |form| %>
    <div>
        <%= form.hidden_field :date_of_rejection, value: @product.date_of_rejection %>
        Браковать с: <%= @product.date_of_rejection %>
    </div>

    <div>
        PLU: <%= form.number_field :plu %>
    </div>

    <div>
        Количество: <%= form.number_field :quantity, min: "0.0", step: "0.001" %>
    </div>

    <div>
        <%= form.radio_button :type_of_quantity, "кг" %>
        <%= form.label :type_of_quantity_kg, 'кг' %>
    </div>

    <div>
        <%= form.radio_button :type_of_quantity, "шт" %>
        <%= form.label :type_of_quantity_sht, 'шт' %>
    </div>

    <div class="file-upload">
    <label>
        <%= form.file_field :photos, accept: 'image/png,image/gif,image/jpeg',
                            onchange: "getFileName();" %>
        <span id="input-text">выбрать фото</span>
    </label>
    </div>

    <div id="file-name"></div>

    <%= form.submit "сохранить" %>
<% end %>

<script type="text/javascript">
    function getFileName() {
        document.getElementById('input-text').innerHTML = "фото выбрано";
    }
</script>

app/views/products/show.html.erb
<div>
    Браковать с: <%= @product.date_of_rejection %>
</div>

<div>
    PLU: <%= @product.plu %>
</div>

<div>
    Количество: <%= @product.quantity %> <%= @product.type_of_quantity %>
</div>

<div>
    <% @product.photos.each do |photo| %>
        <div><%= image_tag photo %></div>
    <% end %>
</div>

<div>
    <%= button_to "добавить фото", add_photo_product_path, method: :get %>
</div>

<div>
    <%= button_to "редактировать", edit_product_path, method: :get %>
</div>

<div>
    <%= button_to "удалить", product_path(@product), method: :delete, 
                  onclick: "return confirm('Точно удалить?')" %>
</div>

<div>
    <%= button_to "вернуться на главную", root_path, method: :get %>
</div>

<div>
    <%= button_to "все товары на продажу", products_path, method: :get %>
</div>

<div>
    <% whatsapp_text = "PLU: #{@product.plu}%0AКоличество: #{@product.quantity} "\
                       "#{@product.type_of_quantity}"%>
    <a href="whatsapp://send/?text=<%= whatsapp_text %>">поделиться через whatsapp</a>
</div>